server:
  port: 8082

spring:
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
  jms:
    servicebus:
      connection-string: Endpoint=sb://kpj-test-chat.servicebus.windows.net/;SharedAccessKeyName=kpj;SharedAccessKey=r2LNwbB181B8RcK8ItIxtco4wbMQIC1Q2+ASbBveXqw=
      # TODO: add connection string
      topic-client-id: JanMaxSlouka
      # TODO: add subscription name (subscriberYourName)
      pricing-tier: standard

logging:
  level:
    cz.inventi.kpj: DEBUG
    org.springframework.messaging: DEBUG
    org.springframework.security: DEBUG
